language: python

install:
  - pip install tox

script:
  - tox

env:
  - TOXENV=py27-django18-coverage
  - TOXENV=py27-django19-coverage
  - TOXENV=py34-django18-coverage
  - TOXENV=py34-django19-coverage

after_success: coveralls